[package]
name = "nginx-cache-purge"
version = "0.1.8"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/nginx-cache-purge"
homepage = "https://magiclen.org/nginx-cache-purge"
keywords = ["nginx", "cache", "clear", "purge", "delete"]
categories = ["command-line-utilities"]
description = "An alternative way to do `proxy_cache_purge` or `fastcgi_cache_purge` for Nginx."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
clap = "2.33.1"
concat-with = "0.2"
terminal_size = "0.1"

md5 = "0.7"
scanner-rust = "2.0.8"